# Generated by Django 3.1.6 on 2021-02-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutData',
            new_name='about',
        ),
    ]
