# Generated by Django 3.1.6 on 2021-02-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210219_0232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='aboutData',
        ),
    ]
