# Generated by Django 3.1.6 on 2021-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210218_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='contact_info',
            new_name='contactForm',
        ),
        migrations.DeleteModel(
            name='contact_form',
        ),
    ]
