# Generated by Django 3.1.6 on 2021-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='slider/')),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='ab_image',
            new_name='image',
        ),
    ]
