# Generated by Django 3.1.6 on 2021-02-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210218_0306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
